### ISSUE TITLE
Icons don't have height in Firefox (using Flexbox) unless set height/width in styles

### ISSUE THREAD

**Issue by KyleAMathews** [gorangajic/react-icon-base#5]
<img width="1251" alt="screen shot 2015-12-07 at 9 41 54 pm" src="https://cloud.githubusercontent.com/assets/71047/11648674/9d99a910-9d2b-11e5-8e60-38fee32b7e4a.png">

I'm guessing the problem has something to do with Flexbox but as I'm quite new to Flexbox, I'm not sure. You can view the problem on relaterocket.co.

@gorangajic would you be open to a PR that adds width/height to `style` as well as attributes?

**Comment by Prinzhorn** [comment]
Could you create a simple demo we can look at?

I think setting width/height via attributes is semantically different from setting it via CSS. It only works coincidentally because the viewBox is a square and width and height are both supplied and are the same. There are plans to only use height (https://github.com/gorangajic/react-icons/issues/11) and let the svg keep its natural ratio (not a square).

**Comment by gorangajic** [comment]
somehow firefox ignore setting height/width attributes in `rem`. You can try setting them to `3.5em` ![ss](https://i.imgur.com/iyFA4pm.png).

I am not sure about that pull request because as @Prinzhorn said there are plans to only use height and remove current `size` prop.
Also you can always pass style props `<Icon style={{height: '3.5rem'}} />`

**Comment by KyleAMathews** [comment]
That's it! Weird bug. Thanks @gorangajic! Ok, I'll close this then and just pass in the height manually.

**Comment by Prinzhorn** [comment]
I believe its not a bug.

The spec for rem unit says

> Equal to the computed value of font-size on the **root element**. When specified on the font-size property of the root element, the rem units refer to the property’s initial value.

http://www.w3.org/TR/css3-values/#rem

Without digging deeper my guess is that since the SVG doesn't actually belong to the HTML spec, the root element in this case _is the <svg> itself_ and not the <html>.

Interestingly the SVG spec does not mention rem at all

> The list of unit identifiers in SVG matches the list of unit identifiers in CSS: em, ex, px, pt, pc, cm, mm and in.

http://www.w3.org/TR/SVG/coords.html#Units

**Comment by KyleAMathews** [comment]
That... would be weird. But it sounds like you're right:

>The svg element can be used to nest a standalone SVG fragment inside the current document (for example an HTML document) as long as the svg is not the root element. This standalone fragment has its own viewport and coordinate system.

from https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg

**Comment by KyleAMathews** [comment]
Certainly not the expected behavior though given that rems work just fine in Chrome/Safari. Seems like an overly rigid interpretation imo.

**Comment by Prinzhorn** [comment]
The point where HTML and SVG collide is a weird space and I'm nowhere near an expert. But since the width/height attributes belong to the SVG their values should obey the rules of the SVG world. The reason is simple: assume child elements like `<path>` use rem. If it would be relative to the `<html>` then the SVG would change depending on the context (e.g. it would look completely different in inkspace/indesign as compared to inline). There is a compromise between "copy the SVG into the HTML and _it just works_" and "I want the SVG to behave like any HTML element".

**Comment by KyleAMathews** [comment]
Yeah, I'm sympathetic to both positions. Thanks for the analysis.

**Comment by gorangajic** [comment]
I think it's just the bug, because when you set width/height using css it work but with attributes it's broken

btw maybe I was not that much clear in my last message apparently `em` works and `rem` does not work, so you can use `em` instead no need to pass styles

**Comment by cameron-martin** [comment]
Would it make sense to make the `size` prop set `style={{ width: props.size, height: props.size }}` on the svg element, so that rems are supported?
